import { z } from "zod";
import { GeneratedBySchema, IdSchema } from "./common";

/**
 * The 9 Rhubarb visemes. A–H are mouth shapes; X is the rest/closed pose.
 * Every puppet ships an image for each of these (ARCHITECTURE §8.2).
 */
export const VISEMES = ["A", "B", "C", "D", "E", "F", "G", "H", "X"] as const;
export const VisemeSchema = z.enum(VISEMES);
export type Viseme = z.infer<typeof VisemeSchema>;

/** A single mouth cue with absolute-in-line start/end seconds. */
export const MouthCueSchema = z.object({
  start: z.number().min(0),
  end: z.number().min(0),
  viseme: VisemeSchema,
});
export type MouthCue = z.infer<typeof MouthCueSchema>;

/**
 * `cues/<lineId>.json` — generated by the optional Rhubarb adapter. Either a bare
 * array of cues or an object wrapping them with provenance; both accepted.
 */
export const MouthCuesFileSchema = z.union([
  z.array(MouthCueSchema),
  z.object({
    generatedBy: GeneratedBySchema.optional(),
    lineId: IdSchema.optional(),
    offset: z.number().min(0).optional(),
    cues: z.array(MouthCueSchema),
  }),
]);
export type MouthCuesFile = z.infer<typeof MouthCuesFileSchema>;
