import { z } from "zod";
import { GeneratedBySchema, IdSchema, MoodSchema } from "./common";

/**
 * `timeline.json` — generated by the canonical audio stage, never hand-edited. The single
 * source of timing truth for music, mix, storyboard resolution, captions, and
 * render duration. All values are absolute seconds from film start except
 * `narrDur`/`dur` which are durations. ARCHITECTURE §6, salvaged shape.
 */
export const TimelineSceneSchema = z.object({
  id: IdSchema,
  name: z.string().optional(),
  display: z.string().optional(),
  mood: MoodSchema.optional(),
  /** Absolute start of the scene (including padBefore). */
  start: z.number().min(0),
  /** Absolute time narration audio begins (start + padBefore). */
  narrAt: z.number().min(0),
  /** Duration of the narration audio itself. */
  narrDur: z.number().min(0),
  /** Full scene duration (padBefore + narrDur + padAfter). */
  dur: z.number().min(0),
  /** Absolute end of the scene (start + dur). */
  end: z.number().min(0),
  /** Per-dialogue-line timing, absolute from film start. */
  dialogue: z.array(z.object({
    id: IdSchema,
    characterId: IdSchema,
    start: z.number().min(0),
    dur: z.number().min(0),
  })).default([]),
});
export type TimelineScene = z.infer<typeof TimelineSceneSchema>;

export const TimelineSchema = z.object({
  generatedBy: GeneratedBySchema.optional(),
  title: z.string().optional(),
  subtitle: z.string().optional(),
  /** Total film duration in seconds; render uses this as an explicit `-t`. */
  total: z.number().min(0),
  scenes: z.array(TimelineSceneSchema),
});
export type Timeline = z.infer<typeof TimelineSchema>;
