import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

/**
 * Thin ComfyUI HTTP client (built-in fetch, no deps). Covers exactly what the
 * image-gen adapter needs: system stats (doctor/health), image upload (edit
 * workflows), prompt submission, /history polling, and /view download.
 */

export interface ComfyImageRef {
  filename: string;
  subfolder: string;
  type: string;
}

export interface ComfyClientOptions {
  baseUrl: string;
  clientId: string;
  /** Poll interval + ceiling for /history (ms). */
  pollIntervalMs?: number;
  timeoutMs?: number;
}

async function fetchWithTimeout(url: string, init: RequestInit, timeoutMs: number): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

export class ComfyClient {
  constructor(private readonly opts: ComfyClientOptions) {}

  private url(path: string): string {
    return `${this.opts.baseUrl.replace(/\/$/, "")}${path}`;
  }

  /** GET /system_stats — used by doctor()/health(); short timeout. */
  async systemStats(): Promise<Record<string, unknown>> {
    const res = await fetchWithTimeout(this.url("/system_stats"), {}, 3000);
    if (!res.ok) throw new Error(`ComfyUI /system_stats returned ${res.status}`);
    return (await res.json()) as Record<string, unknown>;
  }

  /** GET /object_info/<class> — the node's input schema, incl. the model files
   * ComfyUI sees in that loader's folder (used by doctor to verify models). */
  async objectInfo(nodeClass: string): Promise<Record<string, unknown>> {
    const res = await fetchWithTimeout(this.url(`/object_info/${nodeClass}`), {}, 10000);
    if (!res.ok) throw new Error(`ComfyUI /object_info/${nodeClass} returned ${res.status}`);
    return (await res.json()) as Record<string, unknown>;
  }

  /** Upload a local image so an edit workflow's LoadImage node can reference it. */
  async uploadImage(localPath: string): Promise<string> {
    const bytes = readFileSync(localPath);
    const form = new FormData();
    form.append("image", new Blob([bytes]), basename(localPath));
    form.append("overwrite", "true");
    const res = await fetchWithTimeout(this.url("/upload/image"), { method: "POST", body: form }, 30000);
    if (!res.ok) throw new Error(`ComfyUI /upload/image returned ${res.status}`);
    const json = (await res.json()) as { name: string };
    return json.name;
  }

  /** POST /prompt; returns the prompt_id. */
  async submit(graph: unknown): Promise<string> {
    const res = await fetchWithTimeout(
      this.url("/prompt"),
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ prompt: graph, client_id: this.opts.clientId }),
      },
      30000,
    );
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      throw new Error(`ComfyUI /prompt returned ${res.status}. ${body.slice(0, 400)}`);
    }
    const json = (await res.json()) as { prompt_id?: string; error?: unknown };
    if (!json.prompt_id) throw new Error(`ComfyUI /prompt gave no prompt_id: ${JSON.stringify(json).slice(0, 400)}`);
    return json.prompt_id;
  }

  /** Poll /history/<id> until the prompt completes; return output image refs. */
  async awaitImages(promptId: string): Promise<ComfyImageRef[]> {
    const interval = this.opts.pollIntervalMs ?? 1500;
    const deadline = Date.now() + (this.opts.timeoutMs ?? 10 * 60 * 1000);
    // Determinism note: this Date.now() gates a NETWORK wait loop, not manifest
    // or render output — it never influences generated bytes.
    for (;;) {
      const res = await fetchWithTimeout(this.url(`/history/${promptId}`), {}, 10000);
      if (res.ok) {
        const hist = (await res.json()) as Record<string, { outputs?: Record<string, { images?: ComfyImageRef[] }> }>;
        const entry = hist[promptId];
        if (entry?.outputs) {
          const images: ComfyImageRef[] = [];
          for (const out of Object.values(entry.outputs)) {
            for (const img of out.images ?? []) images.push(img);
          }
          if (images.length) return images;
        }
      }
      if (Date.now() > deadline) {
        throw new Error(`ComfyUI: prompt ${promptId} did not produce images within the timeout.`);
      }
      await new Promise((r) => setTimeout(r, interval));
    }
  }

  /** GET /view and write the bytes into outDir; returns the written path. */
  async download(ref: ComfyImageRef, outDir: string, outName?: string): Promise<string> {
    const q = new URLSearchParams({ filename: ref.filename, subfolder: ref.subfolder, type: ref.type });
    const res = await fetchWithTimeout(this.url(`/view?${q.toString()}`), {}, 60000);
    if (!res.ok) throw new Error(`ComfyUI /view returned ${res.status} for ${ref.filename}`);
    const buf = Buffer.from(await res.arrayBuffer());
    mkdirSync(outDir, { recursive: true });
    const dest = join(outDir, outName ?? ref.filename);
    writeFileSync(dest, buf);
    return dest;
  }
}
